(defpackage :trivial-algebra
    (:use #:common-lisp)
  (:nicknames :tral)
  (:export
   ;;; vectors.lisp
   :make-vector
   :do-vector
   :copy-vector
   :map-vector
   :make-random-vector
   :map-two-vectors
   :v+
   :v-
   :v*
   :v+c
   :v-c
   :v*c
   :inner-prod
   :e-norm
   :vector-min
   :vector-max
   :vector-mean
   :norm-vector
   :vector-sum
   :covariance
   ;;; matrix.lisp
   :*default-type*
   :in-type
   :square
   :random-value
   :!
   :make-matrix
   :do-matrix
   :do-row
   :do-col
   :row
   :row-bind
   :col
   :print-matrix
   :copy-matrix
   :map-matrix
   :make-random-matrix
   :map-two-matrices
   :m+
   :m-
   :m*
   :m+c
   :m-c
   :m*c
   :mult-two-matrices
   :m-prod
   :mv-prod
   :v-prod
   :transpose-matrix
   :transpose-vector
   :transpose-vector-into
   :sub-matrix
   :invert-matrix
   :diag
   :make-identity-matrix
   :dim0
   :dim1
   ;;; quaternions.lisp
   :*quaternion-type*
   :make-zero-q
   :make-identity-q
   :make-rotation-q
   :q+
   :q-
   :q*
   :q*c
   :q-norm
   :q-magnitude
   :q-prod
   :q-conjugate
   :q-invert
   :q-rotate-vector))
